# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.caching=false
org.gradle.configuration-cache=false
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true

# Disable built-in Kotlin support to enable standard kotlin-android compiler plugin
android.builtInKotlin=false
android.defaults.buildfeatures.resvalues=true
android.sdk.defaultTargetSdkToCompileSdkIfUnset=false
android.enableAppCompileTimeRClass=false
android.usesSdkInManifest.disallowed=false
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
android.r8.optimizedResourceShrinking=false
android.newDsl=false
org.gradle.vfs.watch=false
kotlin.incremental=false
ksp.incremental=false
ksp.incremental.intermodule=false
org.gradle.parallel=false
